version: "3.9"
services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:${PORT}"
    depends_on:
      - redis
